---
title: "CSS 205/POLI 271 Final Project"
author: "Amy Tan"
format: pdf
editor: visual
execute:
  include: true 
  warning: false
  message: false
---


# Data & Cleaning

```{r echo=FALSE, message=FALSE, warning=FALSE, results='hide'}
# importing relevant libraries
library(haven)
library(tidyr)
library(reshape2)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(MASS)
library(nnet)
library(stargazer)
library(caret)


# Saving study 3 data as s3
s3 <- read_sav('original_data/Study3.sav')

# Data cleaning code provided from authors' Dataverse Rmd
s3$group= factor(s3$SKUPINA, 
                 levels = c(1,2,3,4), 
                 labels = c("Control","Equality", "Reciprocity", "Need"))
s3$SEX <- factor(s3$SEX, 
                 levels = c(1, 2), 
                 labels = c("Male","Female"))
s3$AGECAT= factor(s3$AGECAT, 
                  levels = c(1,2,3,4,5,6), 
                  labels = c("18-24","25-34","35-44", "45-54","55-64","65+"))
s3$EDU= factor(s3$EDU, 
               levels = c(1, 2,3,4), 
               labels = c("Primary","Secondary (no diploma)","Secondary (complete)", "University"))
s3$SIZE= factor(s3$SIZE, 
                levels = c(1, 2,3,4,5), 
                labels = c("less than 1k","1k-4 999","5k-19 999", "20k - 99 999","100k+"))
s3$REG= factor(s3$REG, 
               levels = c(1, 2,3,4,5,6,7,8), 
               labels = c("Bratislavsky","Trnavsky","Trenciansky", "Nitriansky","Zilinsky","Banskobystricky","Presovsky","Kosicky"))

```

## Plotting DV

    ```{r}
    s3$E3 <- as.ordered(s3$E3)

    ggplot(s3, aes(x = E3)) +
           geom_bar(fill = "gray") +
           labs(x = "Completely Disagree (1) - Completely Agree (4)", y = "Frequency") +
           theme_minimal()
    ```

# Original Model (Model 1)

```{r echo=FALSE, message=FALSE, warning=FALSE, results='hide'}

# using Control as the baseline
s3$group <- relevel(s3$group, ref = 'Control')
og_ordered_logit_control <- polr(E3 ~ group, data = s3, Hess=TRUE)

# calculate in-sample performance metrics 
og_ll <- logLik(og_ordered_logit_control)
og_aic <- AIC(og_ordered_logit_control)
og_bic <- BIC(og_ordered_logit_control)

# using Reciprocity as the baseline
s3$group <- relevel(s3$group, ref = 'Reciprocity')
og_ordered_logit_recip  <- polr(E3 ~ group, data = s3, Hess=TRUE)

# regression table for replicated model
stargazer(og_ordered_logit_control, og_ordered_logit_recip,
          type = 'latex',
          column.labels = c("Base = Control", "Base = Reciprocity"),
          dep.var.labels = "DV: Personal Agreement (1-4)",
          covariate.labels = c("Control", "Equality",
                               "Reciprocity", "Need"),
          digits = 2)
```

# An Additional Model (Model 2)

```{r echo=FALSE, message=FALSE, warning=FALSE, results='hide'}
# reset "Control" as the reference category
s3$group <- relevel(s3$group, ref = "Control")
new_ordered_logit  <- polr(E3 ~ group + EDU + SEX + AGE, data = s3, Hess=TRUE)
summary(new_ordered_logit)

# compute in sample metrics for the new ordered logit
new_ol_ll <-logLik(new_ordered_logit)
new_ol_aic <- AIC(new_ordered_logit)
new_ol_bic <- BIC(new_ordered_logit)

# regression table for new model
stargazer(new_ordered_logit,
          type = 'latex',
          column.labels = c("Base = Control"),
          dep.var.labels = "DV: Personal Agreement (1-4)",
          covariate.labels = c("Reciprocity", "Equality", "Need",
                               "Secondary Edu (no diploma)", "Secondary Edu (complete)",
                               "University Edu", "Female"),
          digits = 2)

```

# Comparing Models

    ```{r echo=FALSE, message=FALSE, warning=FALSE, results='hide'}

    set.seed(12345)  # for reproducibility
    trainIndex <- createDataPartition(s3$group, p = 0.70, list = FALSE)
    s3train <- s3[trainIndex, ]
    s3test <- s3[-trainIndex, ]

    og_model_caret <- train(E3 ~ group, data = s3,
                          method = "polr",
                          trControl = trainControl(method = "none"),
                          tuneGrid = data.frame(method = "logistic"))

    new_model_caret <- train(E3 ~ group + EDU + SEX + AGE, 
                          data = s3,
                          method = "polr",
                          trControl = trainControl(method = "none"),
                          tuneGrid = data.frame(method = "logistic"))

    pred1 <- predict(og_model_caret, newdata = s3test)
    pred2 <- predict(new_model_caret, newdata = s3test)

    s3test$result <- factor(s3test$E3, levels = levels(pred1))


    # confusion matrices for out of sample performance
    og_cm <- confusionMatrix(pred1, s3test$E3)
    og_accuracy <- og_cm$overall["Accuracy"]
    new_cm <- confusionMatrix(pred2, s3test$E3)
    new_accuracy <- new_cm$overall["Accuracy"]
    ```

    ```{r echo=FALSE, message=FALSE, warning=FALSE, results='hide'}
    stargazer(og_ordered_logit_control, new_ordered_logit,
              type = 'latex',
              dep.var.labels = "DV: Personal Agreement (1-4)",
              digits = 2,
              covariate.labels = c("Equality", "Reciprocity", "Need",
                                   "Secondary Edu (no diploma)", "Secondary Edu (complete)",
                                   "University Edu", "Female"),
              add.lines = list("In-Sample Performance",
                               c("Log Likelihood", round(og_ll, 2), round(new_ol_ll, 2)),
                               c("AIC", round(og_aic, 2), round(new_ol_aic, 2)),
                               c("BIC", round(og_bic, 2), round(new_ol_bic, 2)),
                               "Out-of-sample Performance",
                               c("Accuracy", round(og_accuracy, 2), round(new_accuracy, 2))
                               
              ))
    ```

# Interpreting Model 2

    ```{r}
    # Get which EDU level is the most common amongst participants
    counts <- table(s3$EDU)
    print(counts)
    ```

    ```{r}

    # scenarios - Reciprocity, Secondary(complete), SEX, mean AGE
    X_female <-  matrix(c(1, 0, 0, 0, 1, 0, 1, mean(s3$AGE)), nrow = 1)  # For SEX = Female
    X_male   <- matrix(c(1, 0, 0, 0, 1, 0, 0, mean(s3$AGE)), nrow = 1)  # For SEX = Male

    # coefficient vectors
    draws <- mvrnorm(1000, c(coef(new_ordered_logit), new_ordered_logit$zeta), 
                     solve(new_ordered_logit$Hessian))
    Beta <- draws[, 1:length(coef(new_ordered_logit))]
    Taus <- draws[, (length(coef(new_ordered_logit)) + 1):ncol(draws)] 

    # predicted probabilities for "completely disagree" category 
    pi_disagree_female <- plogis(Taus[, 1] - Beta %*% t(X_female))
    pi_diagree_male <- plogis(Taus[, 1] - Beta %*% t(X_male))  

    # predicted probabilities for "completely agree" category 
    pi_agree_female <- 1 - plogis(Taus[, 3] - Beta %*% t(X_female)) 
    pi_agree_male <- 1 - plogis(Taus[, 3] - Beta %*% t(X_male)) 

    # differences (first differences between female and male participants)
    fd_disagree <- pi_disagree_female - pi_diagree_male
    fd_agree <- pi_agree_female - pi_agree_male

    # plotting 
    df <- data.frame(
      fd_disagree = fd_disagree,
      fd_agree = fd_agree)

    df_long <- pivot_longer(
      df,
      cols = everything(),
      names_to = "Difference_Type",
      values_to = "Difference")

    df_long$Difference_Type <- factor(
      df_long$Difference_Type, 
      levels = c("fd_disagree", "fd_agree"),
      labels = c("Pr(completely disagree | female) - Pr(completely disagree | male)", 
                 "Pr(completely agree | female) - Pr(completely agree | male)"))

    ggplot(df_long, aes(x = Difference, color = Difference_Type)) +
      geom_density() +
      theme_minimal() +
      labs(
        x = "Change in Predicted Probability") +
      scale_x_continuous(limits = c(-0.15, 0.15))

    ```

